### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YulongNiu** [bengarrett/retrotxtgo#90]
**Describe the bug**
A typo was caught on GitHub readme page.

`retrotext list table cp437 latin1` is corrected as

`retrotxt list table cp437 latin1`

**To Reproduce**
null

**Expected behavior**
null

**Screenshots**
null

**Platform (please complete the following information):**
null

**Additional context**
null

**Comment by bengarrett** [comment]
Thanks!
